spring:
  application:
    name: browser-pilot

browserpilot:
  runtime-dir: ./runtime
  headless: false
  browser-count: 1

  debug:
    persistent: true
    port: 9222

  capture:
    dir: ./page-captures

management:
  endpoints:
    web:
      exposure:
        include: health,info