spring:
  application:
    name: browser-pilot

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

browserpilot:
  runtime-dir: ./runtime

  headless: false

  browser-count: 1

  debug:
    persistent: true
    port: 9222

  capture:
    dir: ./page-captures

management:
  endpoints:
    web:
      exposure:
        include: health,info